version: "3.8"

services:
  mysqldb:
    container_name: noah-system
    image: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: noahdb
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3303:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net: