export const types = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
  LOAD_USER_BY_ID_SUCCESS: 'LOAD_USER_BY_ID_SUCCESS',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  LOAD_NOTICES_ERROR: 'LOAD_NOTICES_ERROR',
  LOAD_ACCOUNT_SUCCESS: 'LOAD_ACCOUNT_SUCCESS',
  CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
};
