version: "3.8"

services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_USER: admin_prod
      MYSQL_PASSWORD: admin12345
      MYSQL_DATABASE: noahdb_prod
      MYSQL_ROOT_PASSWORD: admin12345
    ports:
      - 3305:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net: